server:
  port: 8093

spring:
  jpa:
    hibernate:
      ddl-auto: none

elasticsearch:
  host: ${ELASTICSEARCH_HOST:http://localhost:9200}

monitoring:
  esHealthCheckInterval: 60000

#logging:
#  level:
#    org:
#      springframework: DEBUG

